### ISSUE TITLE
External aips-solr-data volume

### ISSUE THREAD

**Issue by l0rn0r** [treygrainger/ai-powered-search#38]
Hi,
I do not succeed to persist the solr data :(
I added to `ai-powered-search/docker/solr/docker-compose.yml` the following:
```
volumes:
  aips-solr-data:
    name: aips-solr-data
    external: true
```
And I created the volume - output of `docker volume inspect aips-solr-data` is:
```
[
    {
        "CreatedAt": "2021-11-04T14:37:07+01:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/aips-solr-data/_data",
        "Name": "aips-solr-data",
        "Options": {},
        "Scope": "local"
    }
]
```
Any hints/helps?
Thanks in advance!
